stages:
- build-image
- tag-image


variables:
  BUILD_IMAGE: qpr-registry.iti.kit.edu/gbd/gbd:$CI_COMMIT_SHA
  RELEASE_IMAGE: qpr-registry.iti.kit.edu/gbd/gbd:latest

build-image:
  image: docker:stable
  services:
    - docker:dind
  stage: build-image
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  script:
    - docker build -t $BUILD_IMAGE .
    - docker push $BUILD_IMAGE

tag-image:
  image: docker:stable
  services:
    - docker:dind
  stage: tag-image
  tags:
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  script:
    - docker pull $BUILD_IMAGE
    - docker tag $BUILD_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE

