version: "2.4"
services:
  gbd:
    image: udopia/gbd:latest
    environment:
    - VIRTUAL_HOST=localhost
    cpu_count: 4
    mem_limit: 6g
    volumes:
    - /raid/gbd:/raid/gbd:ro
    restart: unless-stopped
    ports:
    - 8642:5000
