[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gbd_tools"
version = "4.9.7"
description = "GBD Tools: Maintenance and Distribution of Benchmark Instances and their Attributes"
readme = "README.md"
requires-python = ">=3.6"
license = { text = "MIT License" }
authors = [
    { name = "Markus Iser", email = "markus.iser@kit.edu" }
]
urls = { Homepage = "https://github.com/Udopia/gbd" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
dependencies = [
    "flask",
    "tatsu",
    "pandas",
    "waitress",
    "pebble",
    "gbdc"
]
scripts = { gbd = "gbd:main" }

[tool.setuptools.packages.find]
where = ["gbd_core", "gbd_init", "gbd_server"]

[tool.setuptools]
include-package-data = true
