version: '3'
services:
  nginx:
    image: udopia/nginx
    #image: mynginx
    environment:
    - VIRTUAL_HOST=benchmark-database.de
    - AWSTATS_USER=statsuser
    - AWSTATS_PASS=stats1234
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - /home/iser/nginx/ssl:/etc/nginx/ssl
    - /home/iser/nginx/ssl/bot:/etc/nginx/ssl/bot

  gbd:
    depends_on:
    - nginx
    image: udopia/gbd
    #image: mygbd
    #environment:
    #- GBD_DB=/gbd/meta.db:/gbd/base.db:/gbd/gate.db
    ports:
    - 44071:44071
    volumes:
    - /home/iser/gbd:/raid/gbd:ro
    restart: always