name: Docker Image CI

on:
#  release:
#    types: [ published ]
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u udopia --password-stdin
#        - name: Get the version
#          id: vars
#          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag udopia/gbd:${{ github.sha }}
        - name: Push the tagged Docker image
          run: docker push udopia/gbd:${{ github.sha }}
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag udopia/gbd:latest
        - name: Push the latest Docker image
          run: docker push udopia/gbd:latest

